### ISSUE TITLE
[Issue] PAPI parsing error (maybe?)

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/Tokens#13]
**Describe the bug**
Not entirely sure what Tokens is trying to do here, but this error is printing to my console: https://pastebin.com/Zkr3L7HE

After printing the above error a few times it went on to print this error once every second to my console until I shut down the server.

[12:59:08] [Server thread/ERROR]: Could not pass event InventoryUpdateEvent to Tokens v2.7.7
java.lang.NullPointerException: null

**To Reproduce**
Not sure

**Server Information (please complete the following information):**
- Tuinity 1.16.3
- Tokens 2.7.7

**Comment by myiume** [comment]
It was parsing the placeholders in inventories that it shouldnt've. Causing issues with other plugins inventories, due to the fact plugins like OpenINV were calling an offline player's inventory. 

I added a double check for the player to be online for the placeholders to work and also fixed the inventory interaction.
