### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by imsalinas** [GC-spigot/Tokens#48]
**Describe the bug**
In the menu.yml when you have an enchantment material set as the same thing as the item whitelist material it removes the enchant and replaces it with the pickaxe in hand.

**To Reproduce**
_EXAMPLE MATERIAL_
Set Efficiency material to GOLDEN_PICKAXE
`material:
        name: GOLDEN_PICKAXE
        data: 0 # Used only if you are server version before 1.13.`

In config.yml set items to GOLDEN_PICKAXE
`  # The list of items that will trigger the menu | Use material names e.g. DIAMOND_PICKAXE | This has a contains, so using PICKAXE will allow all PICKAXES to work
  items:
    - "GOLDEN_PICKAXE"`

**Screenshots / Video**
![2020-11-14_21 30 08](https://user-images.githubusercontent.com/74385959/99162452-95490180-26c3-11eb-9680-f8ac0e5e71aa.png)

https://vimeo.com/user127170151/review/479430101/10f32cd261

**Server Information (please complete the following information):**
 - Minecraft Version: Spigot 1.16.1
- Plugin Version: Tokens-2.9.1-DEV3.jar

**Comment by myiume** [comment]
This cannot be fixed currently because of how the menus work. The material of the pickaxe in hand will always be replaced with the pickaxe item. 

For now, just use a different item there. Nothing I can do to fix this easily at the moment. Will look into remaking this so it doesn't do that anymore in a future rework.
